/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;

import marvin.gui.MarvinImagePanel;
import marvin.image.MarvinImage;
import marvin.io.MarvinImageIO;
import marvin.plugin.MarvinImagePlugin;
import marvin.util.MarvinPluginHistory;
import plugins.HistogramStretching;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Comarch
 */
public class BFrame extends javax.swing.JFrame {

    // GUI
    protected JButton buttonShowHistory;
    protected JButton buttonApply;

    // Marvin Objects
    protected MarvinPluginHistory history;
    protected MarvinImagePlugin tempPlugin;
    protected MarvinImage originalImage;
    protected MarvinImage resultImage;
    protected MarvinImagePanel imagePanelOriginal,
            imagePanelNew;

    public BFrame() {
        initComponents();
    }

    public BFrame(String filename) {
        initComponents();

        imagePanelOriginal = new MarvinImagePanel();
        originalImage = MarvinImageIO.loadImage(filename);
        imagePanelOriginal.setSize(jImagePanel.getWidth(), jImagePanel.getHeight());
        imagePanelOriginal.setImage(originalImage);

        JSplitPane sp1 = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, true, jDataPanel, jImagePanel);
        sp1.setOneTouchExpandable(true);
        sp1.setDividerLocation(150);
        add(sp1);

        jImagePanel.add(imagePanelOriginal);

        /*  Ukrycie komponentow (na pozniej kiedy nie bedziemy na poczatku wczytywac zdjecia odrazu)
         int a = jMenuButtons.getComponentCount();
         for (int i=0;i<a;i++)
         jMenuButtons.getComponent(i).setEnabled(false);
         */
        setVisible(true);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuButtons = new javax.swing.JPanel();
        OpenFile = new javax.swing.JButton();
        SaveFile = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jDataPanel = new javax.swing.JPanel();
        jImagePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MOpenFile = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MSaveFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenuButtons.setPreferredSize(new java.awt.Dimension(781, 105));

        OpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });

        SaveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/write.png"))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Oś X");

        jButton6.setText("Oś Y");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Zaznacz Tytuł");

        javax.swing.GroupLayout jMenuButtonsLayout = new javax.swing.GroupLayout(jMenuButtons);
        jMenuButtons.setLayout(jMenuButtonsLayout);
        jMenuButtonsLayout.setHorizontalGroup(
            jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMenuButtonsLayout.createSequentialGroup()
                        .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMenuButtonsLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jMenuButtonsLayout.setVerticalGroup(
            jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaveFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jMenuButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jMenuButtons, java.awt.BorderLayout.PAGE_START);

        jDataPanel.setBackground(new java.awt.Color(204, 204, 204));
        jDataPanel.setPreferredSize(new java.awt.Dimension(150, 294));

        javax.swing.GroupLayout jDataPanelLayout = new javax.swing.GroupLayout(jDataPanel);
        jDataPanel.setLayout(jDataPanelLayout);
        jDataPanelLayout.setHorizontalGroup(
            jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jDataPanelLayout.setVerticalGroup(
            jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        getContentPane().add(jDataPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jImagePanelLayout = new javax.swing.GroupLayout(jImagePanel);
        jImagePanel.setLayout(jImagePanelLayout);
        jImagePanelLayout.setHorizontalGroup(
            jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jImagePanelLayout.setVerticalGroup(
            jImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        getContentPane().add(jImagePanel, java.awt.BorderLayout.CENTER);

        MOpenFile.setText("Plik");

        jMenuItem2.setText("Otwórz");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MOpenFile.add(jMenuItem2);

        MSaveFile.setText("Zapisz");
        MSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSaveFileActionPerformed(evt);
            }
        });
        MOpenFile.add(MSaveFile);

        jMenuBar1.add(MOpenFile);

        jMenu2.setText("Edycja");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        open();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        open();        // TODO add your handling code here:
    }//GEN-LAST:event_OpenFileActionPerformed

    private void MSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSaveFileActionPerformed
        save();        // TODO add your handling code here:
    }//GEN-LAST:event_MSaveFileActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        save();        // TODO add your handling code here:
    }//GEN-LAST:event_SaveFileActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        preProcessing();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void preProcessing() {
        resultImage = originalImage.clone();
        tempPlugin = new HistogramStretching();
        tempPlugin.setAttribute("hood", 15);
        tempPlugin.setAttribute("sigma", 15);
        tempPlugin.process(resultImage, resultImage);
        resultImage.update();

        imagePanelOriginal.setImage(resultImage);
    }

    /**
     * @param args the command line arguments
     */
    public void open() {
        //System.out.print("dziala");
        FileDialog fd = new FileDialog(this, "Wczytaj", FileDialog.LOAD);
        // Ewentualnie: FileDialog fd =new FileDialog(a,"Zapisz",FileDialog.SAVE);
        fd.setVisible(true);
        String katalog = fd.getDirectory();
        String plik = fd.getFile();
        System.out.println("Ścieżka: " + katalog + plik);

        if (katalog != null && plik != null) {
            originalImage = MarvinImageIO.loadImage(katalog + plik);
            imagePanelOriginal.setImage(originalImage);
        }
    }

    public void save() {
        if (originalImage != null) {
            FileDialog fd = new FileDialog(this, "Zapisz", FileDialog.SAVE);

            fd.setVisible(true);
            String katalog = fd.getDirectory();
            String plik = fd.getFile();

            System.out.println("Ścieżka: " + katalog + plik);
            String filename = katalog + plik;
            MarvinImageIO.saveImage(originalImage, filename);

        }

    }

    //protected abstract void process();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MOpenFile;
    private javax.swing.JMenuItem MSaveFile;
    private javax.swing.JButton OpenFile;
    private javax.swing.JButton SaveFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jDataPanel;
    private javax.swing.JPanel jImagePanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jMenuButtons;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
